title: ummshsh blog
description: >- 
  I don't know anymore
baseurl: "/" 
url: "https://ummshsh.github.io" 
github_username: ummshsh

# Build settings
theme: jekyll-theme-console
plugins:
  - jekyll-paginate-v2

permalink: /:year-:month-:day-:title.:output_ext

# Tag plugin config
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

excerpt_separator: <!--more-->

style: dark #light\hacker
listen_for_clients_preferred_style: true

#paginate: 10
#paginate_path: "/page:num/"

# Collections
collections:
  microblog:
    output: true

# Pagination for microposts (using jekyll-paginate-v2)
pagination:
  enabled: true
  collection: 
    microblog:
      per_page: 5
      sort_reverse: true
      title: "Microblog"
      permalink: /microposts/page:num/

pagination:
  enabled: true
  collection: posts  # This is the default posts collection
  per_page: 10       # Number of posts per page
  sort_reverse: true
  permalink: /page:num/  # URL format for paginated pages


defaults:
  - scope:
      path: ""
      type: "microblog"
    values:
      layout: "micropost"
