name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Ruby
        run: |
        apt-get install ruby-full build-essential zlib1g-dev
        gem install jekyll bundler

      - name: Install
        run: |
        #todo

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site # The folder the action should deploy.
          branch: gh-pages # to which branch